function runHandler(event) {
    event.preventDefault()    
    // AmazingAI - Step 1: Pass userLink to validator.js
    let userLink = document.getElementById('website-url').value.toString();
    console.log("::: New Link Submitted :::");
    Client.runValidator(userLink);
    updateUI();
}

/*  AW - GET Route II: Async fetch data from our app endpoint */
const updateUI = async () => {
    const req = await fetch('/analysis')
    try {
        const findings = await req.json();
        // dynamically fetches data generated by users and weather api from endpoint and dynamcially updates UI.
        document.getElementById('nlp-feedback').innerHTML = "We found some really interesting facts:\n";
        document.getElementById('nlp-subjectivity').innerHTML = "1 - The article is: " + findings.subjectivity.toLowerCase();
        document.getElementById('nlp-confidence').innerHTML = "2 - The author is: " + findings.confidence.toLowerCase() + "% Confident on this topic.";
        document.getElementById('nlp-agreement').innerHTML = "3 - The author is in " + findings.agreement.toLowerCase() + " with the topic.";
    } 
    catch (error) {
        console.log("error", error);
    }
}

export { runHandler }
