import './styles/amazing.scss'
import { checkForName } from './js/nameChecker'
import { handleSubmit } from './js/formHandler'
import icon from './styles/awesome-16x16.png'
import icon from './styles/awesome-32x32.png'

//console.log(checkForName);
alert("Our Express server is running!")

/* Client side POST Route add entry to endpoint
const addToEndpoint = async (url='', data = {}) => {    
    const response = await fetch(url, {
      method: 'POST',
      credentials: 'same-origin',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(data),
    });
    try {
        const newData = await response.json();
        return newData;
    } catch (error) {
        console.log("error", error);
    }
}; */

/* Client side GET Route - Async fetch from endpoint
const updateUI = async () => {
    const req = await fetch('/add-entry');
    try {
        const appData = await req.json();
        // dynamically fetches data generated by users and weather api from endpoint and dynamcially updates UI.
        document.getElementById('date').innerHTML = "The date today is: " + appData.datum;
        document.getElementById('temp').innerHTML = "The temperature is: " + appData.tempum + "°C";
        document.getElementById('content').innerHTML = "You're feeling: '" + appData.feeling + "' today!";
    } catch (error) {
        console.log("error", error);
    }
}; */


export {
    checkForName,
    handleSubmit
}